# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtGui, QtWidgets, QtCore
from PyQt5.QtWidgets import QWidget, QApplication, QLabel, QVBoxLayout, QFileDialog
from PyQt5.QtGui import QPixmap
import sys
import cv2
from PyQt5.QtCore import pyqtSignal, pyqtSlot, Qt, QThread
import numpy as np

class VideoThread(QThread):
    change_pixmap_signal = pyqtSignal(np.ndarray)
    path = ''

    def __init__(self, path):
        super().__init__()
        self._run_flag = True
        self.path = path

    def run(self):
        # capture from web cam
        cap = cv2.VideoCapture(self.path)
        if not cap.isOpened():
            cap = cv2.VideoCapture(0)
        if not cap.isOpened():
            raise IOError('Failed to open video')
        while self._run_flag:
            ret, cv_img = cap.read()
            if ret:
                self.change_pixmap_signal.emit(cv_img)
        # shut down capture system
        cap.release()

    def stop(self):
        """Sets run flag to False and waits for thread to finish"""
        self._run_flag = False
        self.wait()


class Ui_DetectVehicle(object):
    def setupUi(self, DetectVehicle):
        DetectVehicle.setObjectName("DetectVehicle")
        DetectVehicle.resize(298, 458)
        self.centralwidget = QtWidgets.QWidget(DetectVehicle)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_getvideo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_getvideo.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.btn_getvideo.setObjectName("btn_getvideo")
        self.videolable_2 = QtWidgets.QLabel(self.centralwidget)
        self.videolable_2.setGeometry(QtCore.QRect(20, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.videolable_2.setFont(font)
        self.videolable_2.setObjectName("videolable_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widthlcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.widthlcd.setGeometry(QtCore.QRect(70, 110, 81, 23))
        self.widthlcd.setObjectName("widthlcd")
        self.heightlcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.heightlcd.setGeometry(QtCore.QRect(70, 150, 81, 23))
        self.heightlcd.setObjectName("heightlcd")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(110, 70, 75, 23))
        self.btn_start.setObjectName("btn_start")
        self.videolable_5 = QtWidgets.QLabel(self.centralwidget)
        self.videolable_5.setGeometry(QtCore.QRect(10, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videolable_5.setFont(font)
        self.videolable_5.setObjectName("videolable_5")
        self.txt_dict = QtWidgets.QLabel(self.centralwidget)
        self.txt_dict.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.txt_dict.setObjectName("txt_dict")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 280, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 280, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 310, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 340, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 370, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 400, 31, 16))
        self.label_8.setObjectName("label_8")
        self.cardown = QtWidgets.QLabel(self.centralwidget)
        self.cardown.setGeometry(QtCore.QRect(140, 310, 47, 13))
        self.cardown.setObjectName("cardown")
        self.carup = QtWidgets.QLabel(self.centralwidget)
        self.carup.setGeometry(QtCore.QRect(230, 310, 47, 13))
        self.carup.setObjectName("carup")
        self.bikedown = QtWidgets.QLabel(self.centralwidget)
        self.bikedown.setGeometry(QtCore.QRect(140, 340, 47, 13))
        self.bikedown.setObjectName("bikedown")
        self.bikeup = QtWidgets.QLabel(self.centralwidget)
        self.bikeup.setGeometry(QtCore.QRect(230, 340, 47, 13))
        self.bikeup.setObjectName("bikeup")
        self.busdown = QtWidgets.QLabel(self.centralwidget)
        self.busdown.setGeometry(QtCore.QRect(140, 370, 47, 13))
        self.busdown.setObjectName("busdown")
        self.busup = QtWidgets.QLabel(self.centralwidget)
        self.busup.setGeometry(QtCore.QRect(230, 370, 47, 13))
        self.busup.setObjectName("busup")
        self.truckdown = QtWidgets.QLabel(self.centralwidget)
        self.truckdown.setGeometry(QtCore.QRect(140, 400, 47, 13))
        self.truckdown.setObjectName("truckdown")
        self.truckup = QtWidgets.QLabel(self.centralwidget)
        self.truckup.setGeometry(QtCore.QRect(230, 400, 47, 13))
        self.truckup.setObjectName("truckup")
        self.btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quit.setGeometry(QtCore.QRect(210, 70, 75, 23))
        self.btn_quit.setObjectName("btn_quit")
        self.txt_midline = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_midline.setGeometry(QtCore.QRect(150, 200, 113, 20))
        self.txt_midline.setObjectName("txt_midline")
        DetectVehicle.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DetectVehicle)
        self.statusbar.setObjectName("statusbar")
        DetectVehicle.setStatusBar(self.statusbar)

        self.retranslateUi(DetectVehicle)
        QtCore.QMetaObject.connectSlotsByName(DetectVehicle)
        self.btn_getvideo.clicked.connect(self.uploadfile)

    def retranslateUi(self, DetectVehicle):
        _translate = QtCore.QCoreApplication.translate
        DetectVehicle.setWindowTitle(_translate("DetectVehicle", "Vehicle Detection"))
        self.btn_getvideo.setText(_translate("DetectVehicle", "Get Video"))
        self.videolable_2.setText(_translate("DetectVehicle", "Middle Line Position: "))
        self.label.setText(_translate("DetectVehicle", "Width"))
        self.label_2.setText(_translate("DetectVehicle", "Height"))
        self.btn_start.setText(_translate("DetectVehicle", "Start"))
        self.videolable_5.setText(_translate("DetectVehicle", "Detected:"))
        self.txt_dict.setText(_translate("DetectVehicle", "Dict"))
        self.label_3.setText(_translate("DetectVehicle", "DOWN"))
        self.label_4.setText(_translate("DetectVehicle", "UP"))
        self.label_5.setText(_translate("DetectVehicle", "CAR"))
        self.label_6.setText(_translate("DetectVehicle", "MOTORBIKE"))
        self.label_7.setText(_translate("DetectVehicle", "BUS"))
        self.label_8.setText(_translate("DetectVehicle", "TRUCK"))
        self.cardown.setText(_translate("DetectVehicle", "TextLabel"))
        self.carup.setText(_translate("DetectVehicle", "TextLabel"))
        self.bikedown.setText(_translate("DetectVehicle", "TextLabel"))
        self.bikeup.setText(_translate("DetectVehicle", "TextLabel"))
        self.busdown.setText(_translate("DetectVehicle", "TextLabel"))
        self.busup.setText(_translate("DetectVehicle", "TextLabel"))
        self.truckdown.setText(_translate("DetectVehicle", "TextLabel"))
        self.truckup.setText(_translate("DetectVehicle", "TextLabel"))
        self.btn_quit.setText(_translate("DetectVehicle", "QUIT"))
        
   
    def GetVideo(self):
        videoPath = QFileDialog.getOpenFileName(self, 'Open file', 'D:\Giang\3rd Year\2nd Semester\Digital Image Processing\Final Project\Videos', 'Videos (*.mp4)')
        self.thread = VideoThread(videoPath[0])
        self.thread.change_pixmap_signal.connect(self.update_image)
        self.thread.start()

    def closeEvent(self, event):
        self.thread.stop()
        event.accept()



    @pyqtSlot(np.ndarray)
    def update_image(self, cv_img):
        """Updates the image_label with a new opencv image"""
        qt_img = self.convert_cv_qt(cv_img)
        self.image_label.setPixmap(qt_img)
    
    def convert_cv_qt(self, cv_img):
        """Convert from an opencv image to QPixmap"""
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        p = convert_to_Qt_format.scaled(self.disply_width, self.display_height, Qt.KeepAspectRatio)
        return QPixmap.fromImage(p)
     


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DetectVehicle = QtWidgets.QMainWindow()
    ui = Ui_DetectVehicle()
    ui.setupUi(DetectVehicle)
    DetectVehicle.show()
    sys.exit(app.exec_())
